Repository juliojimenez/clickhouse-cl, pull requests merged in 2024-03, with the labels that each got.

#174 Parquet
  .gitignore
  README.md
  clickhouse.asd
  src/ch-sql-parser.lisp
  src/clickhouse.lisp
  src/http.lisp
Labels: documentation, enhancement, test

#176 Fix utils for LispWorks
  src/utils.lisp
Labels: enhancement

#175 Vertical Format
  .github/FUNDING.yml
  README.md
  clickhouse.asd
Labels: documentation, enhancement

#177 README Update
  README.md
Labels: documentation
